apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: 30100
  selector:
    app: kafka-broker
# status:
#   loadBalancer: {}